async function sendToEditor(text,num){if(currentProfile?.account_type!=='verified')return toast('يتطلب حساباً موثقاً');editingNum=num;editingMatnHtml=escHtml(text);editingStatus='draft';footnotes=[];fnCounter=0;currentDraftId=null;renderHadiths(lastRenderedList);if(!currentUser||!currentBook)return;const{data}=await sb.from('user_edits').select('*').eq('user_id',currentUser.id).eq('book_id',currentBook.id).eq('hadith_number',num).maybeSingle();if(String(editingNum)!==String(num))return;if(data){currentDraftId=data.id;editingMatnHtml=data.edited_matn||escHtml(text);footnotes=data.custom_footnotes||[];fnCounter=footnotes.length;editingStatus=data.status;}renderHadiths(lastRenderedList);}
function cancelInlineEdit(){editingNum=null;editingMatnHtml=null;renderHadiths(lastRenderedList);}
function setEditStatus(status){const badge=document.getElementById('edit-status-badge');const labels={draft:'مسودة',pending_review:'قيد المراجعة',approved:'معتمد ✓',rejected:'مرفوض'};badge.textContent=labels[status]||status;badge.className='status-badge status-'+status;}
function fmt(cmd,val=null){document.getElementById('editor-content').focus();document.execCommand(cmd,false,val);}
function pickColor(cmd){const c=prompt(cmd==='foreColor'?'لون الخط (hex):':'لون التظليل (hex):',cmd==='foreColor'?'#c0392b':'#fdf8e8');if(c)fmt(cmd,c);}
function insertSymbol(){const syms=['ﷺ','ﷻ','﷽','ﵟ','ﵞ','ﵠ','ﵡ','رضي الله عنه','رحمه الله','حفظه الله','﴿','﴾'];const s=prompt('اختر رمزاً أو أدخله:\n'+syms.join('  '));if(s){document.getElementById('editor-content').focus();document.execCommand('insertText',false,s);}}
function openFnDialog(){document.getElementById('fn-text-input').value='';openModal('fn-dialog');}
function addFootnote(){const text=document.getElementById('fn-text-input').value.trim();if(!text)return toast('أدخل نص الحاشية');const sel=window.getSelection();fnCounter++;if(sel.rangeCount&&sel.toString()){const range=sel.getRangeAt(0);const ref=document.createElement('sup');ref.className='m-fn-ref';ref.textContent=fnCounter;range.collapse(false);range.insertNode(ref);}footnotes.push({num:fnCounter,text});renderFootnotes();closeModal('fn-dialog');}
function deleteFootnote(num){footnotes=footnotes.filter(f=>f.num!==num);renderFootnotes();}
function renderFootnotes(){const list=document.getElementById('fn-list');list.innerHTML=footnotes.length?footnotes.map(f=>`<div class="fn-item"><span class="fn-num">${f.num}</span><span class="fn-text">${escHtml(f.text)}</span><button class="fn-del" onclick="deleteFootnote(${f.num})">×</button></div>`).join(''):'<div style="font-size:12px;color:#bbb;padding:4px 0">لا حواشي شخصية بعد</div>';}
async function saveDraft(){if(!currentUser||editingNum==null||!currentBook)return toast('لا يوجد حديث محدد');const matn=document.getElementById('editor-content').innerHTML;const payload={user_id:currentUser.id,book_id:currentBook.id,hadith_number:editingNum,edited_matn:matn,custom_footnotes:footnotes,status:'draft',updated_at:new Date().toISOString()};let res;if(currentDraftId)res=await sb.from('user_edits').update(payload).eq('id',currentDraftId);else{res=await sb.from('user_edits').insert(payload).select().single();if(res.data)currentDraftId=res.data.id;}if(res.error)return toast('خطأ في الحفظ');editingStatus='draft';setEditStatus('draft');toast('تم حفظ المسودة في صفحتك الشخصية');}
async function submitForReview(){await saveDraft();if(!currentDraftId)return;const{error}=await sb.from('user_edits').update({status:'pending_review'}).eq('id',currentDraftId);if(error)return toast('خطأ');editingStatus='pending_review';setEditStatus('pending_review');toast('أُرسل للجنة العلمية للمراجعة');}
